export const MIN_AMOUNT_TO_RECEIVE = 1;

// 15 sec.
export const STATE_UPDATE_FREQUENCY = 15 * 1000;

export const STATE_UPDATE_RETRY_FREQUENCY = 1000;

export const MAX_ALLOWED_STATE_DELAY = 30 * 1000;
