/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type OrderStruct = {
  y: PromiseOrValue<BigNumberish>;
  z: PromiseOrValue<BigNumberish>;
  A: PromiseOrValue<BigNumberish>;
  B: PromiseOrValue<BigNumberish>;
};

export type OrderStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber] & {
  y: BigNumber;
  z: BigNumber;
  A: BigNumber;
  B: BigNumber;
};

export type TradeActionStruct = {
  strategyId: PromiseOrValue<BigNumberish>;
  amount: PromiseOrValue<BigNumberish>;
};

export type TradeActionStructOutput = [BigNumber, BigNumber] & {
  strategyId: BigNumber;
  amount: BigNumber;
};

export type PairStruct = {
  id: PromiseOrValue<BigNumberish>;
  tokens: [PromiseOrValue<string>, PromiseOrValue<string>];
};

export type PairStructOutput = [BigNumber, [string, string]] & {
  id: BigNumber;
  tokens: [string, string];
};

export type StrategyStruct = {
  id: PromiseOrValue<BigNumberish>;
  owner: PromiseOrValue<string>;
  tokens: [PromiseOrValue<string>, PromiseOrValue<string>];
  orders: [OrderStruct, OrderStruct];
};

export type StrategyStructOutput = [
  BigNumber,
  string,
  [string, string],
  [OrderStructOutput, OrderStructOutput]
] & {
  id: BigNumber;
  owner: string;
  tokens: [string, string];
  orders: [OrderStructOutput, OrderStructOutput];
};

export interface CarbonControllerInterface extends utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "implementation()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "accumulatedFees(address)": FunctionFragment;
    "calculateTradeSourceAmount(address,address,(uint256,uint128)[])": FunctionFragment;
    "calculateTradeTargetAmount(address,address,(uint256,uint128)[])": FunctionFragment;
    "controllerType()": FunctionFragment;
    "createPair(address,address)": FunctionFragment;
    "createStrategy(address,address,tuple[2])": FunctionFragment;
    "deleteStrategy(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize()": FunctionFragment;
    "pair(address,address)": FunctionFragment;
    "pairs()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "postUpgrade(bytes)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "roleAdmin()": FunctionFragment;
    "roleEmergencyStopper()": FunctionFragment;
    "roleFeesManager()": FunctionFragment;
    "setTradingFeePPM(uint32)": FunctionFragment;
    "strategiesByPair(address,address,uint256,uint256)": FunctionFragment;
    "strategiesByPairCount(address,address)": FunctionFragment;
    "strategy(uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tradeBySourceAmount(address,address,(uint256,uint128)[],uint256,uint128)": FunctionFragment;
    "tradeByTargetAmount(address,address,(uint256,uint128)[],uint256,uint128)": FunctionFragment;
    "tradingFeePPM()": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateStrategy(uint256,tuple[2],tuple[2])": FunctionFragment;
    "version()": FunctionFragment;
    "withdrawFees(address,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "admin"
      | "implementation"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "DEFAULT_ADMIN_ROLE"
      | "accumulatedFees"
      | "calculateTradeSourceAmount"
      | "calculateTradeTargetAmount"
      | "controllerType"
      | "createPair"
      | "createStrategy"
      | "deleteStrategy"
      | "getRoleAdmin"
      | "getRoleMember"
      | "getRoleMemberCount"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "pair"
      | "pairs"
      | "pause"
      | "paused"
      | "postUpgrade"
      | "renounceRole"
      | "revokeRole"
      | "roleAdmin"
      | "roleEmergencyStopper"
      | "roleFeesManager"
      | "setTradingFeePPM"
      | "strategiesByPair"
      | "strategiesByPairCount"
      | "strategy"
      | "supportsInterface"
      | "tradeBySourceAmount"
      | "tradeByTargetAmount"
      | "tradingFeePPM"
      | "unpause"
      | "updateStrategy"
      | "version"
      | "withdrawFees"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTradeSourceAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      TradeActionStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTradeTargetAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      TradeActionStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPair",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createStrategy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      [OrderStruct, OrderStruct]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStrategy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pair",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "pairs", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postUpgrade",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "roleAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "roleEmergencyStopper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roleFeesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingFeePPM",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "strategiesByPair",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "strategiesByPairCount",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "strategy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeBySourceAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      TradeActionStruct[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeByTargetAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      TradeActionStruct[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradingFeePPM",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateStrategy",
    values: [
      PromiseOrValue<BigNumberish>,
      [OrderStruct, OrderStruct],
      [OrderStruct, OrderStruct]
    ]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTradeSourceAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTradeTargetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roleAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleEmergencyStopper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleFeesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingFeePPM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategiesByPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategiesByPairCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeBySourceAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeByTargetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingFeePPM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "FeesWithdrawn(address,address,uint256,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "PairCreated(uint128,address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "StrategyCreated(uint256,address,address,address,tuple,tuple)": EventFragment;
    "StrategyDeleted(uint256,address,address,address,tuple,tuple)": EventFragment;
    "StrategyUpdated(uint256,address,address,tuple,tuple,uint8)": EventFragment;
    "TokensTraded(address,address,address,uint256,uint256,uint128,bool)": EventFragment;
    "TradingFeePPMUpdated(uint32,uint32)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PairCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensTraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradingFeePPMUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface FeesWithdrawnEventObject {
  token: string;
  recipient: string;
  amount: BigNumber;
  sender: string;
}
export type FeesWithdrawnEvent = TypedEvent<
  [string, string, BigNumber, string],
  FeesWithdrawnEventObject
>;

export type FeesWithdrawnEventFilter = TypedEventFilter<FeesWithdrawnEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PairCreatedEventObject {
  pairId: BigNumber;
  token0: string;
  token1: string;
}
export type PairCreatedEvent = TypedEvent<
  [BigNumber, string, string],
  PairCreatedEventObject
>;

export type PairCreatedEventFilter = TypedEventFilter<PairCreatedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface StrategyCreatedEventObject {
  id: BigNumber;
  owner: string;
  token0: string;
  token1: string;
  order0: OrderStructOutput;
  order1: OrderStructOutput;
}
export type StrategyCreatedEvent = TypedEvent<
  [BigNumber, string, string, string, OrderStructOutput, OrderStructOutput],
  StrategyCreatedEventObject
>;

export type StrategyCreatedEventFilter = TypedEventFilter<StrategyCreatedEvent>;

export interface StrategyDeletedEventObject {
  id: BigNumber;
  owner: string;
  token0: string;
  token1: string;
  order0: OrderStructOutput;
  order1: OrderStructOutput;
}
export type StrategyDeletedEvent = TypedEvent<
  [BigNumber, string, string, string, OrderStructOutput, OrderStructOutput],
  StrategyDeletedEventObject
>;

export type StrategyDeletedEventFilter = TypedEventFilter<StrategyDeletedEvent>;

export interface StrategyUpdatedEventObject {
  id: BigNumber;
  token0: string;
  token1: string;
  order0: OrderStructOutput;
  order1: OrderStructOutput;
  reason: number;
}
export type StrategyUpdatedEvent = TypedEvent<
  [BigNumber, string, string, OrderStructOutput, OrderStructOutput, number],
  StrategyUpdatedEventObject
>;

export type StrategyUpdatedEventFilter = TypedEventFilter<StrategyUpdatedEvent>;

export interface TokensTradedEventObject {
  trader: string;
  sourceToken: string;
  targetToken: string;
  sourceAmount: BigNumber;
  targetAmount: BigNumber;
  tradingFeeAmount: BigNumber;
  byTargetAmount: boolean;
}
export type TokensTradedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber, boolean],
  TokensTradedEventObject
>;

export type TokensTradedEventFilter = TypedEventFilter<TokensTradedEvent>;

export interface TradingFeePPMUpdatedEventObject {
  prevFeePPM: number;
  newFeePPM: number;
}
export type TradingFeePPMUpdatedEvent = TypedEvent<
  [number, number],
  TradingFeePPMUpdatedEventObject
>;

export type TradingFeePPMUpdatedEventFilter =
  TypedEventFilter<TradingFeePPMUpdatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface CarbonController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CarbonControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    admin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    implementation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    accumulatedFees(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateTradeSourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateTradeTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    controllerType(overrides?: CallOverrides): Promise<[number]>;

    createPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createStrategy(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      orders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deleteStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMember(
      role: PromiseOrValue<BytesLike>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMemberCount(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[PairStructOutput]>;

    pairs(overrides?: CallOverrides): Promise<[[string, string][]]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    postUpgrade(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    roleAdmin(overrides?: CallOverrides): Promise<[string]>;

    roleEmergencyStopper(overrides?: CallOverrides): Promise<[string]>;

    roleFeesManager(overrides?: CallOverrides): Promise<[string]>;

    setTradingFeePPM(
      newTradingFeePPM: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    strategiesByPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      startIndex: PromiseOrValue<BigNumberish>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[StrategyStructOutput[]]>;

    strategiesByPairCount(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    strategy(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[StrategyStructOutput]>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tradeBySourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      minReturn: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradeByTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      maxInput: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradingFeePPM(overrides?: CallOverrides): Promise<[number]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      currentOrders: [OrderStruct, OrderStruct],
      newOrders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[number]>;

    withdrawFees(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  admin(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  implementation(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  accumulatedFees(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateTradeSourceAmount(
    sourceToken: PromiseOrValue<string>,
    targetToken: PromiseOrValue<string>,
    tradeActions: TradeActionStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateTradeTargetAmount(
    sourceToken: PromiseOrValue<string>,
    targetToken: PromiseOrValue<string>,
    tradeActions: TradeActionStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  controllerType(overrides?: CallOverrides): Promise<number>;

  createPair(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createStrategy(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    orders: [OrderStruct, OrderStruct],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deleteStrategy(
    strategyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMember(
    role: PromiseOrValue<BytesLike>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pair(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<PairStructOutput>;

  pairs(overrides?: CallOverrides): Promise<[string, string][]>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  postUpgrade(
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  roleAdmin(overrides?: CallOverrides): Promise<string>;

  roleEmergencyStopper(overrides?: CallOverrides): Promise<string>;

  roleFeesManager(overrides?: CallOverrides): Promise<string>;

  setTradingFeePPM(
    newTradingFeePPM: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  strategiesByPair(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    startIndex: PromiseOrValue<BigNumberish>,
    endIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<StrategyStructOutput[]>;

  strategiesByPairCount(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  strategy(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<StrategyStructOutput>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tradeBySourceAmount(
    sourceToken: PromiseOrValue<string>,
    targetToken: PromiseOrValue<string>,
    tradeActions: TradeActionStruct[],
    deadline: PromiseOrValue<BigNumberish>,
    minReturn: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradeByTargetAmount(
    sourceToken: PromiseOrValue<string>,
    targetToken: PromiseOrValue<string>,
    tradeActions: TradeActionStruct[],
    deadline: PromiseOrValue<BigNumberish>,
    maxInput: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradingFeePPM(overrides?: CallOverrides): Promise<number>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateStrategy(
    strategyId: PromiseOrValue<BigNumberish>,
    currentOrders: [OrderStruct, OrderStruct],
    newOrders: [OrderStruct, OrderStruct],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<number>;

  withdrawFees(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    implementation(overrides?: CallOverrides): Promise<string>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    accumulatedFees(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTradeSourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTradeTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    controllerType(overrides?: CallOverrides): Promise<number>;

    createPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PairStructOutput>;

    createStrategy(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      orders: [OrderStruct, OrderStruct],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deleteStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMember(
      role: PromiseOrValue<BytesLike>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    pair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PairStructOutput>;

    pairs(overrides?: CallOverrides): Promise<[string, string][]>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    postUpgrade(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    roleAdmin(overrides?: CallOverrides): Promise<string>;

    roleEmergencyStopper(overrides?: CallOverrides): Promise<string>;

    roleFeesManager(overrides?: CallOverrides): Promise<string>;

    setTradingFeePPM(
      newTradingFeePPM: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    strategiesByPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      startIndex: PromiseOrValue<BigNumberish>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<StrategyStructOutput[]>;

    strategiesByPairCount(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    strategy(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<StrategyStructOutput>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tradeBySourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      minReturn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tradeByTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      maxInput: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tradingFeePPM(overrides?: CallOverrides): Promise<number>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      currentOrders: [OrderStruct, OrderStruct],
      newOrders: [OrderStruct, OrderStruct],
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<number>;

    withdrawFees(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "FeesWithdrawn(address,address,uint256,address)"(
      token?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null,
      sender?: null
    ): FeesWithdrawnEventFilter;
    FeesWithdrawn(
      token?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null,
      sender?: null
    ): FeesWithdrawnEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "PairCreated(uint128,address,address)"(
      pairId?: PromiseOrValue<BigNumberish> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null
    ): PairCreatedEventFilter;
    PairCreated(
      pairId?: PromiseOrValue<BigNumberish> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null
    ): PairCreatedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "StrategyCreated(uint256,address,address,address,tuple,tuple)"(
      id?: null,
      owner?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null
    ): StrategyCreatedEventFilter;
    StrategyCreated(
      id?: null,
      owner?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null
    ): StrategyCreatedEventFilter;

    "StrategyDeleted(uint256,address,address,address,tuple,tuple)"(
      id?: null,
      owner?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null
    ): StrategyDeletedEventFilter;
    StrategyDeleted(
      id?: null,
      owner?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null
    ): StrategyDeletedEventFilter;

    "StrategyUpdated(uint256,address,address,tuple,tuple,uint8)"(
      id?: PromiseOrValue<BigNumberish> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null,
      reason?: null
    ): StrategyUpdatedEventFilter;
    StrategyUpdated(
      id?: PromiseOrValue<BigNumberish> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      order0?: null,
      order1?: null,
      reason?: null
    ): StrategyUpdatedEventFilter;

    "TokensTraded(address,address,address,uint256,uint256,uint128,bool)"(
      trader?: PromiseOrValue<string> | null,
      sourceToken?: PromiseOrValue<string> | null,
      targetToken?: PromiseOrValue<string> | null,
      sourceAmount?: null,
      targetAmount?: null,
      tradingFeeAmount?: null,
      byTargetAmount?: null
    ): TokensTradedEventFilter;
    TokensTraded(
      trader?: PromiseOrValue<string> | null,
      sourceToken?: PromiseOrValue<string> | null,
      targetToken?: PromiseOrValue<string> | null,
      sourceAmount?: null,
      targetAmount?: null,
      tradingFeeAmount?: null,
      byTargetAmount?: null
    ): TokensTradedEventFilter;

    "TradingFeePPMUpdated(uint32,uint32)"(
      prevFeePPM?: null,
      newFeePPM?: null
    ): TradingFeePPMUpdatedEventFilter;
    TradingFeePPMUpdated(
      prevFeePPM?: null,
      newFeePPM?: null
    ): TradingFeePPMUpdatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    admin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    implementation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    accumulatedFees(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTradeSourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTradeTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    controllerType(overrides?: CallOverrides): Promise<BigNumber>;

    createPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createStrategy(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      orders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deleteStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: PromiseOrValue<BytesLike>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pairs(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    postUpgrade(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    roleAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    roleEmergencyStopper(overrides?: CallOverrides): Promise<BigNumber>;

    roleFeesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setTradingFeePPM(
      newTradingFeePPM: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    strategiesByPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      startIndex: PromiseOrValue<BigNumberish>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    strategiesByPairCount(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    strategy(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tradeBySourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      minReturn: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradeByTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      maxInput: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradingFeePPM(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      currentOrders: [OrderStruct, OrderStruct],
      newOrders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFees(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    implementation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accumulatedFees(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateTradeSourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateTradeTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    controllerType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createStrategy(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      orders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deleteStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: PromiseOrValue<BytesLike>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pairs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    postUpgrade(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    roleAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    roleEmergencyStopper(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    roleFeesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setTradingFeePPM(
      newTradingFeePPM: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    strategiesByPair(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      startIndex: PromiseOrValue<BigNumberish>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    strategiesByPairCount(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    strategy(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tradeBySourceAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      minReturn: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradeByTargetAmount(
      sourceToken: PromiseOrValue<string>,
      targetToken: PromiseOrValue<string>,
      tradeActions: TradeActionStruct[],
      deadline: PromiseOrValue<BigNumberish>,
      maxInput: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradingFeePPM(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateStrategy(
      strategyId: PromiseOrValue<BigNumberish>,
      currentOrders: [OrderStruct, OrderStruct],
      newOrders: [OrderStruct, OrderStruct],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawFees(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
