export const DFYNV2_FUNCTION_CALL_GAS_COST = 21_000; // Ceiled
export const DFYNV2_TICK_GAS_COST = 24_000; // Ceiled

export const MAX_PRICING_COMPUTATION_STEPS_ALLOWED = 128;

export const DFYNV2_EFFICIENCY_FACTOR = 3;

export const OUT_OF_RANGE_ERROR_POSTFIX = `INVALID_TICK_BIT_MAP_RANGES`;

export const FACTORY_ADDRESS = '';
