export const BEBOP_INIT_TIMEOUT_MS = 5000;
export const BEBOP_PRICES_CACHE_TTL = 10;
export const BEBOP_TOKENS_CACHE_TTL = 60;
export const BEBOP_TOKENS_POLLING_INTERVAL_MS = 30 * 1000;
export const BEBOP_API_URL = 'https://api.bebop.xyz';
export const BEBOP_WS_API_URL = 'wss://api.bebop.xyz';
export const BEBOP_GAS_COST = 120_000;
export const BEBOP_AUTH_NAME = 'paraswap';
export const BEBOP_QUOTE_TIMEOUT_MS = 2000;
